---
autoinstallver: 1
name: node
version: 0.8.19.1-1

excludeext:
  - .md
  - .git
  - .gitignore
installto:
    bin: /usr/local/bin
    include: /usr/local/include
    lib: /usr/local/lib
    share: /usr/local/share

depends:
    - git-core 
    - curl 
    - build-essential 
    - openssl 
    - libssl-dev
exludedir:
    - bin
    - include
    - lib
    - share

installdir: /usr/share/doc/node

tests: t/
